let wordList = [
    { word: "lumipas", hint: "Dumaan ang panahon." },
    { word: "lumalala", hint: "Tumindi o umigting ang kalagayan ng sakit o karamdaman, nagpakita ng higit na masamang sintomas o epekto." },
    { word: "hanapin", hint: "Ang pagkilos o gawain ng pagsisikap na matukoy at matagpuan ang isang bagay, lugar, o tao na nawawala o nais makita o makamtan." },
    { word: "pahamak", hint: "Sinuman o anumang nagiging sanhî ng kabiguan o kapahamakan ng isang táo, panukalà, pamamaraan, balak, atbp." },
    { word: "biyaya", hint: "Anumang natatamo ng isang tao na karaniwang pinasasalamatan sapagkat nakabubuti at kapaki-pakinabang." },
    { word: "baon", hint: "Anumang bagay na dinadalá kapag patúngo sa ibang pook upang magamit (lalo na kung pera, pagkain, at damit)." },
    { word: "kapatagan", hint: "Malawak at patag na lupain, karaniwang taníman ng palay, mais, at iba pang pananim." },
    { word: "limos", hint: "Abuloy na pera at iba pang bagay." },
    { word: "maginoo", hint: "Laláking matikas at may kagalang-galang na katangian." },
    { word: "taglay", hint: "Kalagayan ng pagdadalá o pagkakaroon ng anuman lalo na kung katangian." },
    { word: "pakay", hint: "Anumang kailangan ng isang dumating sa dinatnan." },
    { word: "mabisang", hint: "May kakayahan at nagbibigay ng ninanais na resulta o epekto sa pagtupad ng layunin o kinalabasan ng isang gawain." },
    { word: "nagbilin", hint: "Ang pagbibigay ng panuto, utos, o impormasyon sa isang tao tungkol sa dapat gawin o sundin." },
    { word: "tumanaw", hint: "Ang pagtuon ng paningin sa malayo o sa isang bagay na hindi kalapitan; pagmasid sa lugar o bagay na nasa malayong distansya." },
    { word: "dampa", hint: "Maliit na tahanang tinitirahan ng mga maralita na karaniwang yarì sa marupok na materyales." },
    { word: "pook", hint: "Isang espesipikong bahagi o teritoryo sa mas malawak na espasyo." },
    { word: "ermitanyo", hint: "Táong lumayo at nanirahan sa isang mapanglaw na pook upang mamuhay nang tahimik at maging relihiyoso." },
    { word: "engkantado", hint: "Diwata na may mahiwagang kapangyarihan, naninirahan sa hindi nakikitang kagubatan o kaharian, at nagbibigay ng sumpa o biyaya depende sa pakikitungo sa kanya." },
    { word: "hantinggabi", hint: "Oras sa kalagitnaan ng gabí na ika-12 sa orasán." },
    { word: "dayap", hint: "Isang botanikang sitrus na tumataas hanggang 4 metro, matitinik ang sanga, maputi at mabango ang bulaklak, at may bungang bilugán na maasim ang katas." },
    { word: "sintas", hint: "Panalì na ginagámit sa sapatos." },
    { word: "aalpas", hint: "Makalaya o makatakas mula sa pagkakagapos, pagkakakulong, pagkakatali, o pagkakahawak." },
    { word: "puwesto", hint: "Lugar o dakong sadyang lalagyán ng isang bagay." },
    { word: "masaksihan", hint: "Makita o maging saksí ng anumang pangyayari; mapatunayan sa pamamagitan ng pagkakakita sa nangyari." },
    { word: "kariktan", hint: "Ang katangian o kalidad ng isang bagay o tao na lubos na kaakit-akit, kahanga-hanga, at may natatanging ganda na nakakagawa ng malalim na paghanga." },
    { word: "antok", hint: "Pakiramdam ng isang tao na ibig matulog." }
];
